[bossspectralmodel]
git-tree-sha1 = "eb87b60803fa15faa4121ea9c2ba593360a165bc"
lazy = true

    [[bossspectralmodel.download]]
    sha256 = "6b0dfd6e23f917542311c14c19d3a0e968e40fd598db4c21ed73c17502d391c0"
    url = "https://www.dropbox.com/scl/fi/xppwu70cacqxhbbeh9h31/bossspectramodel.tar.gz?rlkey=lxb1xgvi1qgpbwj0w0fwhur42&dl=0"
